server:
  port: 8080
  host: 0.0.0.0

datasource:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://172.18.0.1:3306/db_system
  username: root
  password: 123456
  pool:
    max-size: 20
    min-size: 5

jpa:
  show-sql: true
  ddl-auto: update
  dialect: org.hibernate.dialect.MySQLDialect